### PR TITLE
mostly erlang code style changes

### PR DESCRIPTION
**Pull request by fenollp**
very interesting article!
`docker-compose` looks amazing

### CODE REVIEW

**Comment by ceejsmith** [comment]
Thanks a lot @fenollp ! That's taught me more about idiomatic Erlang.

Are you able to add a comment to the blog article on www.scottlogic.com? I can then merge this PR and people won't be surprised when the code in the blog post differs from the repo.

**Comment by fenollp** [comment]
Nope, not able.

**Comment by ceejsmith** [comment]
I've just cloned your fork @fenollp and run it and there seems to be a bug? It's not extracting the first character of the path part of the URL.

Should this:

`host_for(<<"GET /", FirstChar:1/binary, _Rest/binary>>) ->`

have FirstChar:8/binary instead? I'm wondering it that just extracts one bit?

**Comment by fenollp** [comment]
Updated.

`_:8/binary` matches 8 bytes because of the `binary`. Replace it with `bits` and it matches 8 bits.

**Pull request merged**
